-- Dogpark schema, migration 0002: paging the read log.
--
-- The read log is the fastest-growing table in the system and the one view
-- whose job is completeness, so it is read with a time range and a keyset
-- cursor rather than a bare `LIMIT`. Ordering is `read_at DESC, rowid DESC`.
--
-- `read_log_agent_read_at` already serves that ordering when a single agent is
-- named — an equality on the leading column, then the index's own order, with
-- the rowid trailing every index key to break ties. Unfiltered, there was no
-- index on `read_at` at all: every page sorted the whole table. This is that
-- index. The trailing rowid comes for free.
CREATE INDEX read_log_read_at ON read_log (read_at);
